### NumPyによる乱数生成 Random sampling with NumPy

#### NumPy randomモジュールのインポート Import numpy and random modules

In [1]:
import numpy as np
import random
import scipy.stats as ss

#### seedを固定したとき In case that a seed is same value

In [2]:
np.random.seed(3)
np.random.randint(low=3,high=10,size=10)

array([5, 3, 4, 6, 3, 3, 3, 8, 8, 6])

In [3]:
np.random.seed(3)
np.random.randint(low=3,high=10,size=10)

array([5, 3, 4, 6, 3, 3, 3, 8, 8, 6])

 #### seedを変えたとき In case that a seed is changed

In [4]:
np.random.seed(4)
np.random.randint(low=3,high=10,size=10)

array([5, 9, 8, 4, 3, 3, 5, 4, 5, 7])

 #### seedを設定しないとき In case that a seed does not given

In [5]:
np.random.randint(low=3,high=10,size=10)

array([8, 9, 4, 3, 7, 5, 7, 9, 9, 5])

In [ ]:
np.random.seed(1)
np.random.nomal(loc=2, scale=3)

In [3]:
ss.norm.pdf(x=25, loc=10, scale=5) - ss.norm.pdf(x=5, loc=10, scale=5)

-0.04750777522144107

In [4]:
ss.norm.pdf(x=70, loc=60, scale=10) - ss.norm.pdf(x=45, loc=10, scale=10)

0.02410980418240976

In [9]:
ss.norm.ppf(q=0.90, loc=60, scale=15)

79.22327348316901

In [13]:
ss.norm.ppf(q=0.75, loc=150.3, scale=5)

153.6724487509804

In [14]:
ss.norm.ppf(q=0.95, loc=150.3, scale=5)

158.52426813475736

In [20]:
1-ss.expon.cdf(x=1, scale=1/2)

0.1353352832366127