## Numpy exercises

### Q1. Import numpy as np and see the version  

In [3]:
import numpy as np
print(np.__version__)

1.14.2


### Q2. Create a 1D array of numbers from 0 to 9

Desired output:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q3. Extract all odd numbers from array arr

input:  
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
output:  
array([1, 3, 5, 7, 9])

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### Q4.  Replace all odd numbers in arr with -1

In [7]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q5. Replace all odd numbers in arr with -1 without changing arr

In [8]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q6. Convert a 1D array to a 2D array with 2 rows

In [9]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q7. Stack arrays a and b vertically

a:  
[[0 1 2 3 4]
 [5 6 7 8 9]]
 
b:
[[1 1 1 1 1]
 [1 1 1 1 1]]
 
Output:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
a = np.arange(10).reshape(2,-1)  # create array a
b = np.repeat(1, 10).reshape(2,-1) # create array b
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
np.concatenate([a, b], axis=0) # Method 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.vstack([a, b]) # Method 2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Q8. Stack the arrays a and b horizontally.

a:  
[[0 1 2 3 4]
 [5 6 7 8 9]]
 
b:
[[1 1 1 1 1]
 [1 1 1 1 1]]
 
Output:

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
a = np.arange(10).reshape(2,-1)  # create array a
b = np.repeat(1, 10).reshape(2,-1) # create array b

In [16]:
np.concatenate([a, b], axis=1) # Method 1

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
np.hstack([a, b]) # Method 2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Q9.  Get the common items between a and b 

a: [1,2,3,2,3,4,3,4,5,6]  
b: [7,2,10,2,7,4,9,4,9,8]

output:
array([2, 4])

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [19]:
np.intersect1d(a,b) 

array([2, 4])

### Q10. From array a remove all items present in array b
a = np.array([1,2,3,4,5])  
b = np.array([5,6,7,8,9])

Output:  
array([1,2,3,4])

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [21]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Q11. Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])  

Output:  
(array([6, 9, 10]),)

In [23]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [25]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [27]:
#  Method 2
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

### Q11. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)  
array([  
[0, 1, 2],  
[3, 4, 5],  
[6, 7, 8]])  
       
Output:  
array([  
[1, 0, 2],  
[4, 3, 5],  
[7, 6, 8]])

In [28]:
arr = np.arange(9).reshape(3,3)

In [29]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Q12. Swap rows 1 and 2 in the array arr

In [31]:
arr = np.arange(9).reshape(3,3)

In [32]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### Q13. Reverse the rows of a 2D array arr.

In [34]:
arr = np.arange(9).reshape(3,3)

In [35]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
### Reverse the rows
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Q14. Reverse the columns of a 2D array arr. 

In [37]:
arr = np.arange(9).reshape(3,3)

In [38]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
### Reverse the columns
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q15. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))

In [40]:
rand_arr = np.random.random((5,3))

In [41]:
rand_arr

array([[0.46598243, 0.28008658, 0.55430243],
       [0.78367436, 0.88034158, 0.23275955],
       [0.49874521, 0.40487607, 0.76919851],
       [0.4707284 , 0.66879001, 0.19344691],
       [0.53737682, 0.78920479, 0.8196588 ]])

In [42]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.466, 0.28 , 0.554],
       [0.784, 0.88 , 0.233],
       [0.499, 0.405, 0.769],
       [0.471, 0.669, 0.193]])

### Q16. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [43]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [44]:
### suppress scientific notation
# Reset printoptions to default
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

### Q17. Import the iris dataset keeping the text intact.

In [45]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [46]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [47]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [48]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

### Q18. Extract the text column species from the 1D iris imported in previous question.

In [52]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding="utf-8")
print(iris_1d.shape)

(150,)


In [50]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

### Q19. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [53]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding="utf-8")

In [54]:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [56]:
# Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])  # <--- options
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

### Q20. Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

 normalization for 1d data  
 
 $$ normalization = \frac{x - min}{max - min} $$

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [58]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

In [59]:
S

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

### Q 21. Find the unique values and the count of unique values in iris's species

In [60]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [61]:
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))