<!-- dom:TITLE: 1クォーターのまとめ　Review and Exercises of 1st quarter -->
# 1クォーターのまとめ　Review and Exercises of 1st quarter
<!-- dom:AUTHOR: 曹巍 Email:cao@iniad.org -->
<!-- Author: -->  
**曹巍** (email: `cao@iniad.org`)

Date: **2018.06.11**

**Summary.** stats1-09では、今まで学習した内容を応用し、自分のスキルを向上させます。  
In stats1-09, you will apply your knowledge and improve the skills you’ve learned 
until now.









# Numpy

### 1.  パッケージ・モジュールをインポットする　Import packages

1. import the numpy pacakge under the name `np`  
2. import the matplotlib's pyplot package under the name `plt`  
3. import the pandas package under the name `pd`   
4. import the random package
5. import the scipy's stats package under the name `ss`
6. import the statsmodels' api package under the name `sm`

(**hint**: import … as …)

In [2]:
### write down your code here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import scipy.stats as ss
import statsmodels as sm

### 2. 要素10個を含めるベクトルを作成し、５番目の要素を１に設定する Create a null vector of size 10 but the fifth value which is 1

X = np.zeros(10) will create a null vector of size 10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Desired output:  
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

(**hint**: np.zeros(), array\[4\])

In [4]:
### write down your code here
X = np.zeros(10)
X[4] = 1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

### 3. 境界部分に1、内部に0を持つ2次元配列を作成する Create a 2d array with 1 on the border and 0 inside

下記のよう配列を作ってください。  
Create the 2d array as follows,  

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]  
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 
 (**hint**: np.ones()関数, np.ones())

In [34]:
### write down your code here
Y = np.ones((10,10))
Y[1:9, 1:9] = 0
Y

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### 4. 1d配列の要素を逆順で表示する。Show elements or an array in reverse order

X = np.arange(50) will generate a 1d array as follows,   
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23  
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47  
 48 49]  

Desired output:  

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26  
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  
  1  0]
 
(**hint**: array[start:stop:step])

In [37]:
### write down your code here
X = np.arange(50)
X[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 5. 0から8までの数字を用いて、3x3のマトリクスを作成する　Create a 3x3 matrix with values ranging from 0 to 8

以下のようなマトリクスを作成しよう。  
[[0 1 2]  
 [3 4 5]  
 [6 7 8]]  

(**hint**: np.reshape())

In [38]:
### write down your code here
X = np.arange(9)
np.reshape(X, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. 10x10 乱数の配列を作成し、その中に最大値と最小値を表示する。Create a 10x10 array with random values and find the minimum and maximum values

(**hint**: np.random.random, min(), max())

In [48]:
### write down your code here
X = np.random.rand(10,10)
print(np.min(X))
print(np.max(X))

0.00608535705165
0.997411749686


### 7. Numpyのスライシング I　Numpy slicing I

X = [[0 1 2]  
     [3 4 5]  
     [6 7 8]]  

Desired output:

[[0 1]  
 [3 4]  
 [6 7]]  

(**hint**: X[rows, cols])

In [58]:
### write down your code here
X = np.arange(9)
Y = np.reshape(X, (3,3))
Y[:, 0:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

### 8. Numpyのスライシング II　Numpy slicing II

X = [[0 1 2]  
     [3 4 5]  
     [6 7 8]]  

Desired output:

[[0 1 2]  
 [3 4 5]]  

(**hint**: X[rows, cols])

In [65]:
### write down your code here
X = np.reshape(np.array([i for i in range(9)]), (3,3))
X[0:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

### 9. Numpyのスライシング　Numpy slicing

X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  

Desired output: 
4  

(**hint**: X[rows, cols])

In [69]:
### write down your code here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
X[1,1]

4

## 要素ごとでの操作　Elementwise operations

### 10. 2つ配列間の要素ごとの差を計算する　Computing element-wised differences between two arrays

x1 = np.array([5, 6, 7, 8])  
x2 = np.array([1, 2, 3, 4])  

x1とx2の間の要素ごとの差:  

4, 4, 4, 4

(**hint**: npは+, -の操作をサポートする、np array supports computations of + and - )

In [70]:
### write down your code here
x1 = np.array([5, 6, 7, 8])
x2 = np.array([1, 2, 3, 4])
x1-x2

array([4, 4, 4, 4])

### 11. 2つ配列間の要素ごとの和を計算する　Computing element-wised sums between two arrays

x1 = np.array([5, 6, 7, 8])  
x2 = np.array([1, 2, 3, 4])  

x1とx2の間の要素ごとの差:  
6, 8, 10, 12

(**hint**: npは+, -の操作をサポートする、np array supports computations of + and - )

In [71]:
### write down your code here
x1 = np.array([5, 6, 7, 8])
x2 = np.array([1, 2, 3, 4])
x1 + x2

array([ 6,  8, 10, 12])

### 12. 2d配列の(列ごとや行ごと)和を計算する　Computing sums by rows or columns for a 2d array

x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])  

列ごとの和(sums by columns):   
6, 8, 10, 12

行ごとの和(sums by rows):   
10
26

<!-- dom:FIGURE: [Figs/axis.png, width=200] -->
<!-- begin figure -->

<p></p>
<img src="Figs/axis.png" width=200>

<!-- end figure -->


(**hint**: axisを指定して、行と列ごとで計算する。conduct row-wised computations via axis option)

In [75]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
### 列ごとの和(sums by columns)
print(np.sum(x, axis=0))
### 行ごとの和(sums by rows):
print(np.sum(x, axis=1))

[ 6  8 10 12]
[10 26]


### 13. 2d配列の最大値と最小値を計算する　find the maximum and minimum in a 2d array

x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])  

1.xの中に最大値と最小値を求めよ Find the maximum and minimum in x:  
最大値: 8  最小値: 1

2.xに対して、行ごとで最大値と最小値を求めよ Find the maximum and minimum in x for rows:  
最大値: 4, 8
最小値: 1, 5

3. xに対して、列ごとで最大値と最小値を求めよ Find the maximum and minimum in x for columns:  
最大値: 5, 6, 7, 8
最小値: 1, 2, 3, 4
(**hint**: axisを指定して、行と列ごとで計算する。conduct row-wised computations via axis option)

In [80]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
### xの中に最大値と最小値を求めよ Find the maximum and minimum in x:  
print(np.min(x),np.max(x))
### xに対して、行ごとで最大値と最小値を求めよ Find the maximum and minimum in x for rows:  
print(np.min(x, axis=1),np.max(x, axis=1))
### xに対して、列ごとで最大値と最小値を求めよ Find the maximum and minimum in x for columns:
print(np.min(x, axis=0),np.max(x, axis=0))

1 8
[1 5] [4 8]
[1 2 3 4] [5 6 7 8]


# Pandas

### 14.  Create pandas's series from 1d list

以下のpythonリスト**x**からPandasのSeries(x_series)に変更して、
'a', 'b', 'c', 'd'をインデックスとして使えるようにしてください。

Create a pandas series named x_series indexed by 'a', 'b', 'c', 'd' from a list
**x** = [10, 20, 30, 40]

In [84]:
### Write down your code here 
x = [10, 20, 30, 40]
x_series =  pd.Series(x, ["a", "b", "c", "d"])

a    10
b    20
c    30
d    40
dtype: int64

### 15.  Create pandas's dataframe from 2d list

以下のpythonリスト**x**からPandasのDataframe(x_dataframe)に変更して、
'a', 'b', 'c', 'd'を列のインデックス、'e','f'を行のインデックスとして
使えるようにしてください。

Create a pandas dataframe named x_dataframe whose columns are indexed by 'a', 'b', 'c', 'd'
and whose rows are indexed by 'e' and 'f' from the following list   
**x** = [[19, 20, 21, 22], [39, 40, 41, 42]]

In [93]:
### Write down your code here 
x = [[19, 20, 21, 22], [39, 40, 41, 42]]
x_dataframe = pd.DataFrame(data=x, columns=["a", "b", "c", "d"],index=["e","f"])

a   b   c   d
e  19  20  21  22
f  39  40  41  42

# リスト内包 List Comprehension
### 16. 要素の２乗 Square of each elements

s = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

sの要素の２乗 (Square of each elements in s):  
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [95]:
### sの要素の２乗 (Square of each elements in s):
s = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[i**2 for i in s]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# numpy's linspace()

### 17. numpy's linspace()

numpyのlinspace() 関数:  ある範囲に対して、等間隔な数列を生成する関数です.  
Function __linspace()__:  Generate an evenly spaced numbers over a specified interval.   

構文: linespace(開始点, 終点, num=50, endpoint=True, retstep=False, dtype=None)  
syntax: linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  


**問題**: linspace()で数列 0, 1, 2, 3, 4, 5を生成します

(Generate a numpy array containing 0,1,2,3,4,5)

In [100]:
### write down your code here
np.linspace(0,5,6)

array([ 0.,  1.,  2.,  3.,  4.,  5.])

# ファイルの読み込みと書き込み　Read and write files

### 18. ファイルの読み込み

1. numpy's loadtxt() 複数列のテキストファイルを読み込みます。

2. numpy's genfromtxt() テキストファイルから数値データを読み込み、欠損値を指定どおりに処理します。

3. pandas' read_csv() 区切られたデータをファイルから読み込みます。 一般に、カンマは区切り記号として使用されます。

4. pandas' read_excel() excelファイルを読み込みます。

データファイル「ToothGrowth.csv」をloadtxt(), genfromtxt()とread_csv()で練習してください。

In [118]:
### loadtxt():
data1 = np.loadtxt("data/ToothGrowth.csv", delimiter=",", comments="!")
### genfromtxt():
data2 = np.genfromtxt("data/ToothGrowth.csv", delimiter=",", comments="!")
### read_csv():
data3 = pd.read_csv("data/ToothGrowth.csv", comment="!")

### 19. ファイルの書き込み

1. numpy's save() 配列をNumPy形式のバイナリファイルに保存します。

2. numpy's savetxt() 配列をテキストファイルに保存する。

以下のような乱数の配列**x**(100x100)を「rand_data.csv」というcsvファイルに書き込んでください。  
**x** = np.random.random((100, 100))

In [119]:
### savetxt():
x = np.random.random((100, 100))
np.savetxt("rand_data.csv", x)